easy_admin:
  entities:
    User:
      class: App\Entity\User
      # Notre controller spécifique
      controller: App\Controller\Admin\User\UserAdminController
      list:
        fields:
          - { property: "email" }
          - { property: "firstname" }
          - { property: "lastname" }
          - { property: "statut.name",label: "Statut" }
      form:
        fields:
          - { property: "email" }
          - property: "plainPassword"
            type: "password"
            type_options: { required: false }
            label: "Password"
          - { property: "firstname" }
          - { property: "lastname" }
          - property: "roles"
            type: "choice"
            type_options:
              mapped: true
              expanded: true
              multiple: true
              choices: { "Administrateur": "ROLE_ADMIN" }
